name: Terraform Plan
on:
  workflow_dispatch:
  push:
    branches: [main]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.BOOTSTRAP_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.BOOTSTRAP_AWS_SECRET_ACCESS_KEY }}
  TF_VAR_ROOT_EMAIL: ${{ secrets.BOOTSTRAP_ROOT_EMAIL }}
  TF_VAR_BOOTSTRAP_GITHUB_TOKEN: ${{ secrets.BOOTSTRAP_GITHUB_TOKEN }}
  TF_VAR_BOOTSTRAP_AWS_ACCOUNT_ID: ${{ secrets.BOOTSTRAP_AWS_ACCOUNT_ID }}
jobs:
  plan:
    runs-on: ubuntu-latest
    if: >-
      !startsWith(github.event.head_commit.message, 'Initial commit') &&
      !startsWith(github.event.head_commit.message, '🤖')
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.4
      - uses: scaffoldly/bootstrap-action@v1
        with:
          action: plan
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          root-email: ${{ secrets.BOOTSTRAP_ROOT_EMAIL }}
          terraform-cloud-token: ${{ secrets.BOOTSTRAP_TERRAFORM_TOKEN }}