name: Render Template
on:
  workflow_dispatch:
    inputs:
      archetect-source:
        description: "Archetype Source Git URL"
        required: true
        default: "https://github.com/scaffoldly/archetype-scaffoldly-bootstrap.git"
      archetect-options:
        description: "Archetect Render Options"
        required: false

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: scaffoldly/archetect-render-action@1.0.0-12
        with:
          source: "${{ github.event.inputs.archetect-source }}"
          options: "${{ github.event.inputs.archetect-options }}"
      - uses: scaffoldly/bump-version-action@v1
        with:
          action: prerelease
          version-file: "${{ github.event.inputs.version-file }}"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
