name: Render Template
on:
  workflow_dispatch:
    inputs:
      archetect-source:
        description: "Archetype Source Git URL"
        required: true
      archetect-options:
        description: "Archetect Render Options"
        required: false

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: scaffoldly/archetect-render-action@1.0.2-4
        with:
          source: "${{ github.event.inputs.archetect-source }}"
          options: "${{ github.event.inputs.archetect-options }}"
